pipeline {
    agent any

    environment {
        // --- KONFIGURASI DOCKER HUB (WAJIB GANTI) ---
        DOCKER_REGISTRY_USER = 'kasih04'
        
        // Nama Image & Tag
        SERVICE_NAME         = 'notification-service'
        IMAGE_TAG            = '1.0'
        
        // Gabungan: kasih04/notification-service:1.0
        FULL_IMAGE_NAME      = "${DOCKER_REGISTRY_USER}/${SERVICE_NAME}:${IMAGE_TAG}"
        
        // ID Credential di Jenkins
        DOCKER_CRED_ID       = 'docker-hub-credentials'

        // --- KONFIGURASI KUBERNETES ---
        // Folder source code (Sesuai script Anda)
        PROJECT_DIR    = 'PerpustakaanService/notificationservice' 
        
        // Nama Deployment & Container di file YAML Kubernetes
        K8S_DEPLOYMENT = 'notification-deployment'
        K8S_NS         = 'perpustakaan-ns'
        CONTAINER_NAME = 'notification-container'
    }

    // Menggunakan tool Maven 'maven-3'
    tools {
        maven 'maven-3'
    }

    stages {
        // Stage 'Initialize' DIHAPUS karena menyebabkan error Permission Denied.
        // Jenkins biasanya sudah siap pakai.

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Maven') {
            steps {
                dir("${PROJECT_DIR}") {
                    // Build file .jar
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build & Push Docker') {
            steps {
                dir("${PROJECT_DIR}") {
                    script {
                        // Login Otomatis ke Docker Hub + Build + Push
                        docker.withRegistry('', DOCKER_CRED_ID) {
                            
                            echo "Building image: ${FULL_IMAGE_NAME}"
                            def customImage = docker.build(FULL_IMAGE_NAME)
                            
                            echo "Pushing image to Docker Hub..."
                            customImage.push()
                        }
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    echo "Updating Kubernetes Deployment..."
                    
                    // 1. Update image di deployment ke versi kasih04
                    sh """
                    kubectl set image deployment/${K8S_DEPLOYMENT} \
                    ${CONTAINER_NAME}=${FULL_IMAGE_NAME} \
                    -n ${K8S_NS}
                    """
                    
                    // 2. Restart Deployment agar perubahan diterapkan
                    sh "kubectl rollout restart deployment/${K8S_DEPLOYMENT} -n ${K8S_NS}"
                    
                    // 3. Verifikasi status
                    sh "kubectl rollout status deployment/${K8S_DEPLOYMENT} -n ${K8S_NS}"
                }
            }
        }
    }
    
    post {
        always {
            // Bersihkan image sampah
            sh 'docker image prune -f'
        }
    }
}